---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: reimb-api-deployment
  labels:
    app: project1-reimb-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: project1-reimb-api
  template:
    metadata:
      labels:
        app: project1-reimb-api
    spec:
      containers:
        - image: olvmky/reimb-api
          imagePullPolicy: Always
          name: project1-reimb-api
          ports:
            - containerPort: 8888
          livenessProbe:
            httpGet:
              path: /hw
              port: 8888
          readinessProbe:
            httpGet:
              path: /hw
              port: 8888
---
apiVersion: v1
kind: Service
metadata:
  name: reimb-api-service
spec:
  selector:
    app: project1-reimb-api
  type: NodePort
  ports:
    - port: 8888
      targetPort: 8888


